src/main/java/DOM/FacturaManagedBean.java
package DOM;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.Map;
import java.util.HashMap;

import org.apache.log4j.Logger;
import org.hibernate.Session;
import org.hibernate.Transaction;

import hbm.Factura;
import hbm.Cliente;
import hbm.Guia;
import util.HibernateUtil;

public class FacturaManagedBean implements Serializable
{

    private static final long serialVersionUID = 1L;
    private static Logger log = Logger.getLogger(FacturaManagedBean.class);
    private static final String SUCCESS = "success";
    private static final String ERROR   = "error";

    private String ruc_empresa;
    private int id_cliente;
    private Date fecha;
    private float valor;
    private boolean pagado;
    private String factura;
    private String empresa;
    private List<Guia> guiasFactura = new ArrayList<Guia>();



    private Factura facturaO;

    private List<Factura> filteredFacturas;

    public List<Factura> getFilteredFacturas() {
        return filteredFacturas;
    }

    public void setFilteredFacturas(List<Factura> filteredFacturas) {
        this.filteredFacturas = filteredFacturas;
    }

    public Factura getFacturaO()
    {
        return facturaO;
    }

    public void setFacturaO(Factura facturaO)
    {
        this.facturaO = facturaO;
    }



    public String getRuc_empresa()
    {
        return this.ruc_empresa;
    }

    public void setRuc_empresa(String ruc_empresa)
    {
        this.ruc_empresa = ruc_empresa;
    }

    public int getId_cliente()
    {
        return this.id_cliente;
    }

    public void setId_cliente(int id_cliente)
    {
        this.id_cliente = id_cliente;
    }

    public void setFecha(Date fecha)
    {
        this.fecha = fecha;
    }

    public Date getFecha()
    {
        return fecha;
    }

    public void setValor(float valor)
    {
        this.valor = valor;
    }

    public float getValor()
    {
        return this.valor;
    }

    public void setPagado(boolean pagado)
    {
        this.pagado = pagado;
    }

    public boolean getPagado()
    {
        return this.pagado;
    }

    public String getFactura()
    {
        return this.factura;
    }

    public void setFactura(String factura)
    {
        this.factura = factura;
    }

    public String getEmpresa()
    {
        return this.empresa;
    }

    public void setEmpresa(String empresa)
    {
        this.empresa = empresa;
    }

    public void setGuiasFactura(List<Guia> guiasFactura)
    {
        this.guiasFactura = guiasFactura;
    }

    public List<Guia> getGuiasFactura()
    {
        return guiasFactura;
    }


    public String save()
    {
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        // Cliente
        ClienteManagedBean cmb = new ClienteManagedBean();
        Cliente cliente = (Cliente) session.load(Cliente.class,
                cmb.getIdCliente(this.getRuc_empresa()));


        Factura factura = new Factura();
        factura.setFecha(new Date());
        factura.setValor(this.getValor());
        factura.setPagado(false);
        factura.setCliente(cliente);

        // Agregar factura al cliente
        cliente.getFacturas().add(factura);

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.save(factura);
            tx.commit();
            log.debug("Nuevo registro : " + factura + ", realizado : " + tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }

    public List<Factura> getFacturas()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        List<Factura>  facturaList = session.createCriteria(Factura.class).list();
        return facturaList;
    }

    public List<Factura> getFacturasPendientes()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        List<Factura>  facturaList = session.createCriteria(Factura.class).list();
        List<Factura> facturaPendList = new ArrayList<Factura>();
        for (Factura f : facturaList)
        {
            if (!f.isPagado())
            {
                facturaPendList.add(f);
            }
        }
        return facturaPendList;
    }

    public void reset()
    {
        this.setFecha(new Date());
        this.setValor(0);
        this.setPagado(false);
    }









    public String pagar()
    {
        this.setFactura(String.valueOf(this.getFacturaO().getId()));
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        Factura factura = (Factura) session.load(Factura.class,
                Integer.parseInt(this.getFactura()));

        factura.setPagado(true);

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.update(factura);
            tx.commit();
            log.debug("Nuevo registro : " + factura + ", realizado : " +
                      tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }

    public Map<String, String> getUnpaidFacturas()
    {
        List<Factura> facturaList = this.getFacturas();
        Map<String, String> descripciones = new  HashMap<String, String>();

        for (Factura f : facturaList)
        {
            if (!f.isPagado())
            {
                descripciones.put(f.getCliente().getNombre_empresa() + " | $" +
                        Float.toString(f.getValor()),
                        Integer.toString(f.getId()));
            }
        }

        return descripciones;
    }

    public Map<String, String> getFacturasDescripcion()
    {
        List<Factura> facturaList = this.getFacturas();
        Map<String, String> descripciones = new  HashMap<String, String>();

        for (Factura f : facturaList)
        {
            descripciones.put(f.getCliente().getNombre_empresa() + " | $" +
                    Float.toString(f.getValor()), Integer.toString(f.getId()));

        }

        return descripciones;
    }

    public void onFacturaChange()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Factura factura = (Factura) session.load(Factura.class,
                Integer.parseInt(this.getFactura()));

        List<Guia> guias = new ArrayList<Guia>();
        guias.addAll(factura.getGuias());

        this.setFecha(factura.getFecha());
        this.setEmpresa(factura.getCliente().getNombre_empresa());
        this.setValor(factura.getValor());
        this.setPagado(factura.isPagado());
        this.setGuiasFactura(guias);
    }

    public void onFacturaChangeT()
    {
        this.setFactura(String.valueOf(this.getFacturaO().getId()));
        this.onFacturaChange();
    }
}

src/main/java/DOM/RutaManagedBean.java
package DOM;

import java.io.Serializable;
import java.util.List;
import java.util.Iterator;
import java.util.Map;
import java.util.HashMap;

import org.apache.log4j.Logger;
import org.hibernate.Session;
import org.hibernate.Transaction;

import hbm.Ruta;
import util.HibernateUtil;

public class RutaManagedBean implements Serializable
{

    private static final long serialVersionUID = 1L;
    private static Logger log = Logger.getLogger(RutaManagedBean.class);
    private static final String SUCCESS = "success";
    private static final String ERROR   = "error";

    private float tarifa;
    private String origen;
    private String destino;
    private String transporte;
    private boolean habilitado;
    private String ruta;


    private Ruta rutaO;

    private List<Ruta> filteredRutas;

    public List<Ruta> getFilteredRutas() {
        return filteredRutas;
    }

    public void setFilteredRutas(List<Ruta> filteredRutas) {
        this.filteredRutas = filteredRutas;
    }

    public Ruta getRutaO()
    {
        return rutaO;
    }

    public void setRutaO(Ruta rutaO)
    {
        this.rutaO = rutaO;
    }




    public float getTarifa()
    {
        return tarifa;
    }

    public void setTarifa(float tarifa)
    {
        this.tarifa = tarifa;
    }


    public String getOrigen()
    {
        return origen;
    }

    public void setOrigen(String origen)
    {
        this.origen = origen;
    }

    public String getDestino()
    {
        return destino;
    }

    public void setDestino(String destino)
    {
        this.destino = destino;
    }

    public String getTransporte()
    {
        return transporte;
    }

    public void setTransporte(String transporte)
    {
        this.transporte = transporte;
    }

    public boolean isHabilitado()
    {
        return habilitado;
    }

    public void setHabilitado(boolean habilitado)
    {
        this.habilitado = habilitado;
    }

    public String getRuta()
    {
        return ruta;
    }

    public void setRuta(String ruta)
    {
        this.ruta = ruta;
    }


    public String save()
    {
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        Ruta ruta = new Ruta();
        ruta.setTarifa(this.getTarifa());
        ruta.setOrigen(this.getOrigen());
        ruta.setDestino(this.getDestino());
        ruta.setTransporte(this.getTransporte());
        ruta.setHabilitado(true);

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.save(ruta);
            tx.commit();
            log.debug("Nuevo registro : " + ruta + ", realizado : " +
                      tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }

    public List<Ruta> getRutas()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        List<Ruta>  rutaList = session.createCriteria(Ruta.class).list();
        return rutaList;
    }

    public void reset()
    {
        this.setTarifa(0);
        this.setOrigen("");
        this.setDestino("");
        this.setTransporte("");
        this.setHabilitado(true);
    }






    public String deshabilitar()
    {
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        Ruta ruta = (Ruta) session.load(Ruta.class,
                Integer.parseInt(this.getRuta()));

        ruta.setHabilitado(false);

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.save(ruta);
            tx.commit();
            log.debug("Nuevo registro : " + ruta + ", realizado : " +
                      tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }

    public String habilitar()
    {
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        Ruta ruta = (Ruta) session.load(Ruta.class,
                Integer.parseInt(this.getRuta()));

        ruta.setHabilitado(true);

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.save(ruta);
            tx.commit();
            log.debug("Nuevo registro : " + ruta + ", realizado : " +
                      tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }

    public Map<String, String> getRutasHabilitados()
    {
        List<Ruta> rutaList = this.getRutas();
        Map<String, String> descripciones = new  HashMap<String, String>();

        for (Ruta p : rutaList)
        {
            if (p.isHabilitado())
            {
                descripciones.put(p.getDescripcion(),
                        Integer.toString(p.getId()));
            }
        }

        return descripciones;
    }

    public Map<String, String> getRutasDeshabilitados()
    {
        List<Ruta> rutaList = this.getRutas();
        Map<String, String> descripciones = new  HashMap<String, String>();

        for (Ruta p : rutaList)
        {
            if (!p.isHabilitado())
            {
                descripciones.put(p.getDescripcion(),
                        Integer.toString(p.getId()));
            }
        }

        return descripciones;
    }


    public Ruta getRutaByID(String id)
    {
        List<Ruta> rutas = getRutas();

        for (Ruta ruta : rutas)
        {
            if (ruta.getId() == Integer.parseInt(id))
            {
                return ruta;
            }
        }

        return null;
    }

    public Map<String, String> getRutasDescripcion()
    {
        List<Ruta>  rutaList = this.getRutas();
        Map<String, String> descripciones = new  HashMap<String, String>();

        for (Ruta r : rutaList)
        {
            if (r.isHabilitado())
            {
                descripciones.put(r.getDescripcion(), Integer.toString(r.getId()));
            }
        }

        return descripciones;
    }

    public void onRutaChange()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Ruta ruta = (Ruta) session.load(Ruta.class,
                Integer.parseInt(this.getRuta()));

        this.setTarifa(ruta.getTarifa());
        this.setOrigen(ruta.getOrigen());
        this.setDestino(ruta.getDestino());
        this.setTransporte(ruta.getTransporte());
    }

    public void onRutaChangeT()
    {
        this.setRuta(String.valueOf(this.getRutaO().getId()));
        this.onRutaChange();
    }

    public String modificar()
    {
        this.setRuta(String.valueOf(this.getRutaO().getId()));
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        Ruta ruta = (Ruta) session.load(Ruta.class,
                Integer.parseInt(this.getRuta()));

        ruta.setTarifa(this.getTarifa());
        ruta.setOrigen(this.getOrigen());
        ruta.setDestino(this.getDestino());
        ruta.setTransporte(this.getTransporte());
        ruta.setHabilitado(true);

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.update(ruta);
            tx.commit();
            log.debug("Nuevo registro : " + ruta + ", realizado : " +
                      tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }
}

src/main/webapp/agregar-cliente.xhtml
<ui:composition template="index.xhtml"
                
                xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:define name="Nuevo">
 <h:panelGrid columns="3" cellpadding="100">
                <p:panel header="Nuevo cliente">
                    <h:form>
                        <table>
                            <tr>
                                <td><h:outputLabel for="ruc_empresa" value="Ruc empresarial:" /></td>
                                <td><p:inputText id="ruc_empresa" value="#{clienteMBean.ruc_empresa}"/></td>
                            </tr>
                            <tr>
                                <td><h:outputLabel for="nombre_empresa" value="Nombre empresa:" /></td>
                                <td><p:inputText id="nombre_empresa" value="#{clienteMBean.nombre_empresa}"/></td>
                            </tr>
                            <tr>
                                <td><h:outputLabel for="cedula_representante" value="Cedula representante:" /></td>
                                <td><p:inputText id="cedula_representante" value="#{clienteMBean.cedula_representante}"/></td>
                            </tr>
                            <tr>
                                <td><h:outputLabel for="nombre_representante" value="Nombre representante:" /></td>
                                <td><p:inputText id="nombre_representante" value="#{clienteMBean.nombre_representante}"/></td>
                            </tr>
                            <tr>
                                <td><h:outputLabel for="telefono" value="Teléfono:" /></td>
                                <td><p:inputText id="telefono" value="#{clienteMBean.telefono}"/></td>
                            </tr>
                            <tr>
                                <td><h:outputLabel for="direccion" value="Dirección:" /></td>
                                <td><p:inputText id="direccion" value="#{clienteMBean.direccion}"/></td>
                            </tr>
                            <tr>
                                <td><h:outputLabel for="password" value="Contraseña:" /></td>
                                <td><p:password id="password" value="#{clienteMBean.password}"/></td>
                            </tr>
                            <tr>
                                <td><p:commandButton id="submit" value="Guardar" action="#{clienteMBean.save}" update="growl" ajax="false"/></td>
                                <td><p:commandButton id="reset" value="Resetear" action="#{clienteMBean.reset}" ajax="false"/></td>
                            </tr>
                        </table>
                    </h:form>
                </p:panel>
            </h:panelGrid>
    </ui:define>
      
</ui:composition>

src/main/webapp/agregar-evento.xhtml
<ui:composition template="index.xhtml"
               
    xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:define name="Agregar">
    <p:panel header="Agregar Evento">
        <h:form id="main">


        <p:dataTable id="guia" var="guia"
            value="#{guiaMBean.guias}"
            widgetVar="guiasTable" emptyMessage="Guias no encontrados con
            ese criterio" filteredValue="#{eventoMBean.filteredGuias}"
            rows="20" paginator="true" paginatorTemplate="{CurrentPageReport}
            {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink}
            {LastPageLink} {RowsPerPageDropdown}"
            rowsPerPageTemplate="5,10,20,50"
            resizableColumns="false" liveResize="true" selectionMode="single"
            selection="#{eventoMBean.guiaO}" rowKey="#{guia.id}">

            <f:facet name="header">
                <p:outputPanel>
                    <h:outputText value="Guia" />
                    <br/>
                    <br/>
                    <h:outputText value="Buscar en todos los campos:  " />
                    <p:inputText id="globalFilter"
                        onkeyup="PF('guiasTable').filter()"
                        style="width:150px" placeholder="Ingrese palabara"/>
                </p:outputPanel>
            </f:facet>

            <p:column filterBy="#{guia.cliente.ruc_empresa}" headerText="Ruc Empresa"  filterMatchMode="contains">
                    <h:outputText value="#{guia.cliente.ruc_empresa}" />
            </p:column>
            <p:column filterBy="#{guia.cliente.nombre_empresa}" headerText="Empresa"  filterMatchMode="contains">
                    <h:outputText value="#{guia.cliente.nombre_empresa}" />
            </p:column>
            <p:column filterBy="#{guia.ruta.descripcion}" headerText="Ruta"  filterMatchMode="contains">
                <h:outputText value="#{guia.ruta.descripcion}" />
            </p:column>
            <p:column filterBy="#{guia.paquete.descripcion}" headerText="Paquete"  filterMatchMode="contains">
                <h:outputText value="#{guia.paquete.descripcion}" />
            </p:column>
        </p:dataTable>



            <br/>
            <hr/>
            <br/>
            
            
                
            <p:outputLabel for="evento" value="Evento:" />
                    <p:selectOneRadio id="evento" value="#{eventoMBean.evento}">
                <br/>
                <f:selectItem itemLabel="Salida" itemValue="Salida"/>
                <br/>
                <f:selectItem itemLabel="Llegada" itemValue="Llegada"/>
                <br/>
                <f:selectItem itemLabel="Entregado" itemValue="Entregado"/>
                <br/>
                <f:selectItem itemLabel="Aprobado" itemValue="Aprobado"/>
                <br/>
                <f:selectItem itemLabel="Rechazado" itemValue="Rechazado"/>
                <br/>
                <f:selectItem itemLabel="Retornado" itemValue="Retornado"/>
                <br/>
                <f:selectItem itemLabel="Punto de control" itemValue="Punto de
                control"/>
                        </p:selectOneRadio>
<table>
                    <tr>
                        <td><h:outputLabel for="descripcion" value="Descripción [opcional]:" /></td>
                        <td><p:inputTextarea rows="6" cols="33" id="descripcion" value="#{eventoMBean.descripcion}"/></td>
                    </tr>
            </table>
            <p:commandButton id="submit" value="Guardar" action="#{eventoMBean.save}" ajax="false"/>
            <p:commandButton id="reset" value="Resetear" action="#{eventoMBean.reset}" ajax="false"/>

     </h:form>
     </p:panel>
    </ui:define>
</ui:composition>

src/main/webapp/agregar-ruta.xhtml
<ui:composition template="index.xhtml"
               
                xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:define name="Nuevo">
  <h:panelGrid columns="3" cellpadding="100">
                <p:panel header="Nuevo Ruta">      
    
    <h:form>
         <table>
             <tr>
                <td><h:outputLabel for="tarifa" value="Tarifa:" /></td>
                <td><p:inputText id="tarifa" value="#{rutaMBean.tarifa}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="origen" value="Origen:" /></td>
                <td><p:inputText id="origen" value="#{rutaMBean.origen}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="destino" value="Destino:" /></td>
                <td><p:inputText id="destino" value="#{rutaMBean.destino}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="transporte" value="Transporte:" /></td>
                <td><p:inputText id="transporte" value="#{rutaMBean.transporte}"/></td>
             </tr>


             <tr>
                <td><p:commandButton id="submit" value="Guardar" action="#{rutaMBean.save}" ajax="false"/></td>
                <td><p:commandButton id="reset" value="Resetear" action="#{rutaMBean.reset}" ajax="false"/></td>
             </tr>
         </table>
     </h:form>
     </p:panel>
  </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/habilitar-ruta.xhtml
<ui:composition template="index.xhtml"
              
                xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:define name="Habilitar">
        <h:panelGrid columns="3" cellpadding="100">
 
    <p:panel header="Habilitar ruta">
    <h:form>
        <table>

            <tr>
                <td><p:outputLabel for="ruta" value="Tipo de ruta: " /></td>
        
        <td><p:selectOneMenu id="ruta" value="#{rutaMBean.ruta}" style="width:150px">
            <f:selectItems value="#{rutaMBean.rutasDeshabilitados}" />
        </p:selectOneMenu></td>
            </tr>
        </table>
    
    <hr/>
    <br/>
        <p:commandButton id="submit" value="Habilitar" action="#{rutaMBean.habilitar}" ajax="false"/>

     </h:form>
     </p:panel>
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/listar-facturas.xhtml
<ui:composition template="index.xhtml"
               
    xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:define name="Listar">
        <h:form id="main">


        <p:dataTable id="factura" var="factura"
            value="#{facturaMBean.facturasPendientes}"
            widgetVar="facturasTable" emptyMessage="Facturas no encontrados con
            ese criterio" filteredValue="#{facturaMBean.filteredFacturas}"
            rows="20" paginator="true" paginatorTemplate="{CurrentPageReport}
            {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink}
            {LastPageLink} {RowsPerPageDropdown}"
            rowsPerPageTemplate="5,10,20,50"
            resizableColumns="false" liveResize="true" selectionMode="single"
            selection="#{facturaMBean.facturaO}" rowKey="#{factura.id}">

            <p:ajax event="rowSelect"
                listener="#{facturaMBean.onFacturaChangeT}"
                update=":main:cliente :main:fecha :main:total :main:guias"/>


            <f:facet name="header">
                <p:outputPanel>
                    <h:outputText value="Factura" />
                    <br/>
                    <br/>
                    <h:outputText value="Buscar en todos los campos:  " />
                    <p:inputText id="globalFilter"
                        onkeyup="PF('facturasTable').filter()"
                        style="width:150px" placeholder="Ingrese palabara"/>
                </p:outputPanel>
            </f:facet>

            <p:column filterBy="#{factura.cliente.ruc_empresa}" headerText="Ruc Empresa"  filterMatchMode="contains">
                    <h:outputText value="#{factura.cliente.ruc_empresa}" />
            </p:column>
            <p:column filterBy="#{factura.cliente.nombre_empresa}" headerText="Empresa"  filterMatchMode="contains">
                    <h:outputText value="#{factura.cliente.nombre_empresa}" />
            </p:column>
            <p:column filterBy="#{factura.valor}" headerText="Valor"  filterMatchMode="contains">
                <h:outputText value="#{factura.valor}" />
            </p:column>
        </p:dataTable>



        <br/>
        <br/>
        <hr/>
        <br/>
        <table>
            <tr>
                <td><h2>Detalles de la Factura</h2></td>
                        </tr>


            <tr>
                <td><h:outputText value="Cliente: "></h:outputText></td>
        
                <td><h:outputText id="cliente" value="#{facturaMBean.empresa}"></h:outputText></td>
            </tr>
            <tr>
                <td><h:outputText value="Fecha: "></h:outputText></td>
        
        <td><h:outputText id="fecha" value="#{facturaMBean.fecha}"></h:outputText><br/></td>
            </tr>
            <tr>
                <td><h:outputText value="Total: "></h:outputText></td>
        
                <td><h:outputText id="total" value="#{facturaMBean.valor}"></h:outputText></td>
            </tr>
        </table>
        <br/>
        <br/>
        <p:dataTable id="guias" value="#{facturaMBean.guiasFactura}" var="guia" style="width: 100%">
            <p:column>
                <f:facet name="header">
                    <h:outputText value="ID" />
                </f:facet>
                <h:outputText value="#{guia.id}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Detalle" />
                </f:facet>
                <h:outputText value="#{guia.detalle}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Paquete" />
                </f:facet>
                <h:outputText value="#{guia.paquete.getDescripcion}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Ruta" />
                </f:facet>
                <h:outputText value="#{guia.ruta.getDescripcion}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Valor" />
                </f:facet>
                <h:outputText value="#{guia.getValor}" />
            </p:column>
        </p:dataTable>

        </h:form>

    </ui:define>
</ui:composition>